# Generated by Django 5.2.8 on 2025-11-15 14:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100)),
                ('biography', models.TextField()),
            ],
            options={
                'unique_together': {('first_name', 'last_name', 'patronymic')},
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year_release', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('genre', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('fiction', 'Художественная литература'), ('textbook', 'Учебник')], max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='book_covers/')),
                ('text_file', models.FileField(upload_to='book_texts/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestApiBooks.author')),
            ],
            options={
                'unique_together': {('title', 'author', 'year_release', 'publisher')},
            },
        ),
    ]
